# Generated by Django 2.1.5 on 2019-01-11 06:36

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import doc_scanner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_list', djongo.models.fields.ArrayModelField(model_container=doc_scanner.models.FileLoc)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAppConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=300)),
                ('project_id', models.CharField(max_length=300)),
                ('auth_uri', models.CharField(max_length=300)),
                ('token_uri', models.CharField(max_length=300)),
                ('auth_provider_x509_cert_url', models.CharField(max_length=300)),
                ('client_secret', models.CharField(max_length=300)),
                ('redirect_uris', models.CharField(max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('google_drive', 'Google Drive'), ('remote', 'Remote System')], default='google_drive', max_length=20)),
                ('drive_userId', models.EmailField(blank=True, max_length=254)),
                ('drive_auth_token', models.CharField(blank=True, editable=False, max_length=300)),
                ('drive_refresh_token', models.CharField(blank=True, editable=False, max_length=300)),
                ('drive_access_token', models.CharField(blank=True, editable=False, max_length=300)),
                ('drive_token_expiry', models.CharField(blank=True, editable=False, max_length=100)),
                ('remote_systemIP', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_username', models.CharField(blank=True, max_length=100)),
                ('remote_password', models.CharField(blank=True, max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='filesaddress',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_scanner.Source'),
        ),
    ]
