# Generated by Django 2.1.5 on 2019-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_scanner', '0002_source_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
