# Generated by Django 2.1.5 on 2019-01-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_scanner', '0003_auto_20190112_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=300)),
                ('user_img_url', models.URLField(blank=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('google_drive', 'Google Drive'), ('remote_system', 'Remote System')], default='google_drive', max_length=20),
        ),
        migrations.AddField(
            model_name='driveuserinfo',
            name='user_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_scanner.Source'),
        ),
    ]
