# Generated by Django 2.1.5 on 2019-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_scanner', '0004_auto_20190114_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='drive_token_expiry',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
